### ISSUE TITLE
Display Order Change Request

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#347]
When 01 General Information.ps1 runs, it displays the results (HTML output) in an order that doesn't seem to have any rhyme or reason.  I wanted it to be displayed in a more logical hierarchical order.  Would you consider changing the display order of the 10 items?
Here are the code changes that I made to change the order:
`
-------------------------------------------
    $Info = New-Object -TypeName PSObject -Property @{
       "1-Number of Clusters" = (@($Clusters).Count)
       "2-Number of vSphere Hosts" = (@($VMH).Count)
       "3-Number of Datastores" = (@($Datastores).Count)
       "4-Total Number of VMs" = (@($VM).Count)
       "5-Active VMs (Powered on)" = (@($FullVM | Where { $_.Runtime.PowerState -eq "poweredOn" }).Count) 
       "6-In-active VMs (Powered off)" = (@($FullVM | Where { $_.Runtime.PowerState -eq "poweredOff" }).Count)
       "7-Number of Templates" = (@($VMTmpl).Count)
    }
    
    # Don't display DRS line if 0 days are set
    if ($DRSMigrateAge -gt 0) {
       $Info | Add-Member Noteproperty "8-DRS Migrations for last $($DRSMigrateAge) Days" (@($MigrationQuery1 | Where {$_.GetType().Name -eq "DrsVmMigratedEvent"}).Count)
    }
    
    # Adding vSphere 5 informations
    if ($VIVersion -ge 5) {
       $Info | Add-Member Noteproperty "9-Number of Datastore Clusters" $(@($DatastoreClustersView).Count)
       if ($SDRSMigrateAge -gt 0) {
          $Info | Add-Member Noteproperty "10-Storage DRS Migrations for last $($SDRSMigrateAge) Days" (@($MigrationQuery2 | Where {$_.FullFormattedMessage -imatch "(Storage vMotion){1}.*(DRS){1}"}).Count)
       }
    }
    
    $Info | Select "1-Number of Clusters","2-Number of vSphere Hosts","3-Number of Datastores","4-Total Number of VMs","5-Active VMs (Powered on)","6-In-active VMs (Powered off)","7-Number of Templates","8-DRS Migrations for last $($DRSMigrateAge) Days","9-Number of Datastore Clusters","10-Storage DRS Migrations for last $($SDRSMigrateAge) Days"
-------------------------------------------
`

P.S., is there a way that I can submit a code segment in this forum without "MARKDOWN" reformatting it?

**Comment by Sneddo** [comment]
Need to have a think about this one, there may be a better way to do this...

> P.S., is there a way that I can submit a code segment in this forum without "MARKDOWN" reformatting it?
Yep, either enclose in backticks or indent by four spaces

**Comment by vScripter** [comment]
This should be able to be solved by creating the object a bit differently. If you create the object like:
```
$Info = [PSCustomObject] @{
  "Number of Clusters" = (@($Clusters).Count)
  "Number of vSphere Hosts" = (@($VMH).Count)
  "Number of Datastores" = (@($Datastores).Count)
  "Total Number of VMs" = (@($VM).Count)
  "Active VMs (Powered on)" = (@($FullVM | Where { $_.Runtime.PowerState -eq         "poweredOn" }).Count) 
  "In-active VMs (Powered off)" = (@($FullVM | Where { $_.Runtime.PowerState -eq "poweredOff" }).Count)
  "Number of Templates" = (@($VMTmpl).Count)
}
```

This will return the results and maintain the order that you specify when you declare/create the object and remove the need to send the object to `Select-Object` in order to format the output. 

That said, I am converting objects to the syntax I detailed above, wherever I can, throughout the project. 

Also, we should try to avoid creating object property names with spaces; generally speaking, it becomes a pain to handle and filter output.

@MasterChiefJon, if you want to submit changes, please submit them to the `dev` branch.

For the sake of cleaning up outstanding issues in order to 'clean house' and prepare for some new development tracks, I am going to close this; if it's still an issue we can re-open/re-visit. Thanks!
