### ISSUE TITLE
Move $Server from GlobalVariables to Init plugin

### ISSUE THREAD

**Issue by Sneddo** [alanrenouf/vCheck-vSphere#359]
This makes more sense to define in the connect plugin, and keep GlobalSettings as configuration of vCheck core only. 

Will require modifying vCheck.ps1 (variable check part), globalVariables.ps1 (remove setting), and 00 Connection Plugin for vCenter.ps1 (Add setting).

This may cause a few Issues being logged as people upgrade vCheck.

**Comment by PaulWalkerUK** [comment]
This is a good idea. I don't have it on front of me at the moment, but I seem to recall that this is also printed at the top of the reports. If so, will the style.ps1 files also need changing?

**Comment by Sneddo** [comment]
Yeah it is in the header, but as long as we keep the $Server variable name we should be fine.

**Comment by PaulWalkerUK** [comment]
I'm just thinking though, if the objective is to eliminate dependencies between vCheck core and the plugins, this change won't really achieve all that much if the style.ps1 files still refer to that variable.

In my own personal use-case (which I admit is probably unusual), I don't use any of the provided plugins. Because I run essentially the same tests against multiple environments, I actually use the existing $server variable more as a "report title" so I can see which environment a report is for.

**Comment by Sneddo** [comment]
hmmmm good point... perhaps having an actual report title setting in global variables might be an idea.

**Comment by PaulWalkerUK** [comment]
That works for me. Then like you suggested, move $server into the connection plugin and display the new title variable on the report. 

If you wanted to make sure that anyone upgrading didn't lose the server name from the report, you could always check to see if the new title variable is null in the connection plugin - if so, set it to $server. Or just make the new report title compulsory

**Comment by Sneddo** [comment]
I think no matter how we handle it it will break something for someone, but at least it is a simple fix (and really the worst it should do is just not display a heading).

We really need a more robust update mechanism to get around these issues... e.g. having vCheck update itself, and have a pre/post upgrade script to handle things like adding the title variable to globalvariables. Of course, this would be made a lot simpler with updated settings handling that does not rely on modifying plugin files... hmmmmm...

**Comment by rkleijwegt** [comment]
It has been a while since I last checked the vCheck code updates. But this one stands out because it breaks one of the most valuable features: the use of job files. And I felt like I needed to address this. By moving the vCenter server settings to the connection plugin means that I can no longer have a global variable that is set on a per job basis.

Let me give an example.

Right now I'm able to create 2 jobs targeted at different vCenter instances and using a different set of plugins like this:
1. Create a file called MyJob.xml and enter the location of the GlobalVariables file which can be named as MyJob_GlobalVariables.ps1. And in that ps1 file I can configure my vCenter instance of choice.
2. With minimal effort I can target another vCenter instance by creating another set of xml and ps1 files and using a different vCenter instance in the GlobalVariables file.

With the new setup I would need to create a different vCheck directory or copy the Init plugin a few times to target another server. And that seems less efficient. Or is there another way?

**Comment by Sneddo** [comment]
Well, the idea was to generalise vCheck so that only variables that relate to the generation of the report are in GlobalVariables. This means vCheck can be used for any reporting task, not specifically vSphere.

Of course, the second part of this change hasn't happened yet, which is the complete rewrite of the settings handling to get rid of the GlobalVariables file altogether... Issue #361 touches on this.
