### ISSUE TITLE
SnapReminder

### ISSUE THREAD

**Issue by Stev3O** [alanrenouf/vCheck-vSphere#360]
Not sure if you can help Alan!

Using Snap reminder for several months Brilliant script!

See Attached screenshot
However for no apparent reason it stopped working.  Looks like it is failing to get the Creator out of VMware. I added the following:-
   Write-Host "----------Snap name--------------"
   Write-Host $SnapshotInfo.Name
   Write-Host "----------Description--------------"
   Write-Host $SnapshotInfo.description
   Write-Host "----------Creator--------------"
   Write-Host $SnapshotInfo.Creator

to print to screen for Snap name, Description and creator.

You will see  2 different snaps but no creator found therefore it will not send an email

![snap_search_capture](https://cloud.githubusercontent.com/assets/11942803/7136424/ab9404ae-e2a8-11e4-8154-d264542a23b9.PNG)

**Comment by Sneddo** [comment]
Looks like it is either not finding the user, or they do not have an email address.

Though, since this is unrelated to vCheck I will close this off. 

You could try contacting Alan via his [website](http://www.virtu-al.net/), [twitter](http://www.twitter.com/alanrenouf), or the [VMware PowerCLI communities](https://communities.vmware.com/community/vmtn/automationtools/powercli)
