### ISSUE TITLE
vCPU/pCPU ratio seems not correct

### ISSUE THREAD

**Issue by willemdh** [alanrenouf/vCheck-vSphere#396]
Hello,

Just ran the vCheck report for the first time yesterday. Thanks for all the work that was put in it!

But I noticed something strange. The report syas the vCPU/pCPU ratio is 1 for some cluster. We recently calculated this ourselves and we came to a value of 2. Another cluster also has a vCPU/pCPU ratio of 1 and we calculated this a 1.9. 
I was wondering what might be the cause of this difference. Does vCheck takes hyperthreading into account? We were told that hyperthreading should not be taken into account and our vCPU/pCPU ratio of 2 needs to be improved by assigning less cpu's to our vm's (or buying more esx servers) . But comparing this with the vCPU/pCPU ration vCheck is giving us, I'm starting to wonder if this is really necessary.
I was also wondering if the value in vCheck report is an integer (as I only seem to see round numbers. Wouldn't this better be a float ideally?

Thanks for shedding some light on this.

Willem

**Comment by Sneddo** [comment]
Which plugin are you talking about specifically?

In general I believe Hyperthreading will be counted, as this is the recommendation for VMware to have it enabled (otherwise, why would you not just turn it off). Although it is not the same as another core, the performance benefit to having it enabled outweighs this. 

I'm not sure why you're so worried about your ratio being up around 2 unless you have really active VMs. Yes, you will potentially start getting CPU contention above 1:1, but really unless you are seeing CPU ready time getting excessive I wouldn't worry about it. Hell, on one of our clusters we have a ratio on around 4:1, but these VMs sit idle the majority of the time...

**Comment by willemdh** [comment]
Hey Sneddo,

Thanks for your explanation. I'm talking about the 20 Cluster\71 Capacity Planning.ps1 plugin. Of course hyperthreading is enabled. We were told by our supplier that the vCPU / pCPU ratio should be lower then 1.5 without taking hyperthreading into account. 
My main concern about the vCPU / pCPU ratio is that it is not a deciaml number. Imho there is a big difference between a  vCPU / pCPU ratio of 1 and a  vCPU / pCPU ratio of 1.5?
I'll look into it and see if I can implement this myself so the  vCPU / pCPU ratio is a decimal in the report.

**Comment by Sneddo** [comment]
Simple enough fix, just need to change one character on the round function. I agree we should either make it a decimal or display a more accurate ratio (e.g. 1:1.5 or 2:3)
