### ISSUE TITLE
Report pulls up VM/HOST Alarm description as "System.object"

### ISSUE THREAD

**Issue by vbakshi123** [alanrenouf/vCheck-vSphere#471]
When I run the script, the output for the VM & Host Alarms has the description as "System.Object[]".
Also, all the server names are twice in each row for all the Alarms, example "HA Configuration issue", "DRS Rule" "Host configuration issues", "Host Alarms", "Snapshot Information", "Invalid or Inaccessible VM" "No VM Tools", "VM Tools issues", "VM Alarms", "Snapshots Oversize".
I am only pulling the reports for the above categories, because that is all I need. Need some help with this. 
Attached sample screenshot

https://cloud.githubusercontent.com/assets/20863238/17443891/bab7197c-5b5a-11e6-9a84-85019970dc95.png

**Comment by vbakshi123** [comment]
Can anyone please help ??

**Comment by Sneddo** [comment]
Let's start with the basics: what versions of Powershell, PowerCLI, vCheck, and plugins are you running?

Do you have vCenters in linked mode? Were you running vCheck from a fresh session, or were you already connected to vCenter(s)?

Looking at the plugin code, the issue seems to be the dupicate host/VM as this then returns an array of alarms. These plugins probably needs revisiting to see if there is a better way too achieve the same result...

**Comment by vbakshi123** [comment]
Thanks Sneddo, yes there were duplicate VCenters. Its resolved now, even the "System Object" description pulls up the right one. One small problem that I am facing is with the email subject. The $EmailSubject = "$Server vCheck Report" in GlobalVariables.ps1 is not picking up the $Server variable which is already declared in the "00 Connection Plugin for vCenter.ps1"  file. Could you throw some light on this

**Comment by vbakshi123** [comment]
Adding to the below

The DatastoreInformation.ps1 pulls up the datastore capacity and free space as 0 , but percent free shows correct. Similar is for SnapshotInformation.ps1, the snapshot size shows 0, though everything else shows fine. Attached are the screenshots

![image](https://cloud.githubusercontent.com/assets/20863238/17563744/6071d752-5f4e-11e6-9fc6-de1b19cd16aa.png)

![image](https://cloud.githubusercontent.com/assets/20863238/17563757/688c6128-5f4e-11e6-973b-034891ba2cd4.png)

**Comment by Sneddo** [comment]
$Server in the email subject won't work since we generalised vCheck by shifting the server parameter from globalVariables.ps1 to the connection plugin. This is because globalVariables.ps1 is evaluated before $server is set in the connection plugin. Until the settings handling gets an overhaul, you will need to put the server name in directly.

Datastores- could it be a rounding issue? Can you try running `Get-Datastore | select name, FreeSpaceMB, CapacityMB` and confirm that the correct size is shown?

Snapshots could very well be 0GB (or at least something that gets rounded to this). e.g. if it was taken when powered off and not powered on again afterwards. Again, it may be a rounding issue as well. As a side note: do you really have 3 year old snapshots? That's...impressive!

**Comment by vbakshi123** [comment]
Thank you for explaining the $server variable. 
Regarding the datastore space, I found that it works on a different Vcenter where powercli 5.5 is installed, but it pulls the values as 0 on powercli 4.1. The issue is the MB and GB, if I pull FreeSpaceMB, CapacityMB, it works, but GB won't work and it pulls 0. probably powercli 4.1 didn't have the GB feature yet embedded. 

Could you help me in knowing how to run it for multiple vcenters in one script, but shoot multiple emails. 
How to get the html output saved locally while running the script

**Comment by Sneddo** [comment]
hmmm interesting. Might be worth adding a warning into vCheck for older versions of PowerCLI, there are some huge benefits to running the latest and greatest.

There isn't any way to run multiple vCenters and send the individual results, to do this you would need to use a [job file](https://github.com/alanrenouf/vCheck-vSphere/wiki/Job-XML-Specification). To save a copy you can use the $Outputpath parameter to specify a location to store the report (by default it goes to the temp directory)
