### ISSUE TITLE
Come hack on vCheck with me!

### ISSUE THREAD

**Issue by alanrenouf** [alanrenouf/vCheck-vSphere#476]
If you are at VMworld and want to come hack on vCheck, make sure you join up for my team here:

[https://code.vmware.com/2016/08/08/come-join-hackathon/](https://code.vmware.com/2016/08/08/come-join-hackathon/)

Eat Pizza, Drink Beer and Code!

If your not at VMworld but want to join in then you can simply add ideas here that we can think about when we are there, perhaps something you have been wishing was in vCheck?

Looking forward to your suggestions and potentially working with you at VMworld!

**Comment by Sneddo** [comment]
Love to be there, but will have to settle for suggestions :)

The big ones for me would be:
1. Update settings handling as discussed in issue #361
2. Config GUI - especially to add scheduled tasks with known working config since this comes up all the time.
3. Move data collection out of a plugin and only collect objects as required. This may help with that persistent 'underlying connection closed' bug, and speed things up a bit. Have plugins call a function to return the objects they require, and that function gathers the objects as required, caching them for additional lookups.
4. Expand filtering options. This would be easiest once the above has been completed potentially. There's been quite a few requests for this over the past years. e.g. filtering to certain datacenters. Issue #169
